# Generated by Django 2.0.6 on 2018-07-07 22:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('animal', models.CharField(max_length=250)),
                ('age', models.PositiveIntegerField()),
                ('size', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('breed', models.CharField(max_length=30)),
                ('altered', models.BooleanField()),
                ('shots', models.BooleanField()),
                ('special_needs', models.BooleanField()),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Shelter'),
        ),
    ]
